
//USER

GET http://localhost:3030/user

####

POST http://localhost:3030/user
Content-Type: application/json

{
    "firstName":"damiano3",
    "lastName":"pavon3",
    "email":"damianopavon3@gmail.com",
    "password":"1234525563"
}

####
PATCH http://localhost:3030/user/661fd1e6a7bc6be8f5d00d6e
Content-Type: application/json

{
     "firstName":"Damiano",
     "lastName": "Pavon"
}

####
DELETE http://localhost:3030/user/661fd1e6a7bc6be8f5d00d6e





//PRODUCT

####
GET http://localhost:3030/product

####
GET http://localhost:3030/product/men


####
GET http://localhost:3030/product/women

####
GET http://localhost:3030/product/661fda17414c6ca89cc14063

####
POST http://localhost:3030/product
Content-Type: application/json

{
    "image":"https://res.cloudinary.com/dp7v6spca/image/upload/v1715282415/PRODUCTS/s6aetvxrayeojswwks7h.webp",
    "title":"Pantaloni uomo nero quadri eleganti casual slim fit in cotone Principe di Galles",
    "price":"30",
    "description":" Pantaloni neri comodi ed eleganti ",
    "category":"Uomo"
    
}

####
PATCH  http://localhost:3030/product/66367d842d44554fdd21b533
Content-Type: application/json

{
    "image":"https://res.cloudinary.com/dp7v6spca/image/upload/v1714848859/PRODUCTS/luc6mfsxvvz8swhbzhyu.jpg"
}

####
DELETE http://localhost:3030/product/661fda17414c6ca89cc14063


//LOGIN
####
POST  http://localhost:3030/login
Content-Type: application/json

{
    "email":"damianopavon3@gmail.com",
    "password":"1234525563"
}